#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OmTV.Resource", IsApplication=true)]

namespace OmTV
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate_centre = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int About = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Browse = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Exit = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Letter = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Notification = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Preferences = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Refresh = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int FlyOutContainer = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int FlyOutContent = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int FlyOutMenu = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int MenuButton = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int RefreshButton = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int aboutBtn = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int exitBack = 2131099663;
			
			// aapt resource value: 0x7f060008
			public const int iView = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int iViewAbout = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int lViewPlaylist = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int layoutExit = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int layoutPlaylistitem = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int tViewAbout = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int tViewNewCnt = 2131099657;
			
			// aapt resource value: 0x7f060010
			public const int tViewPlaylistTitle = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int tViewTitle = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int writeMeBtn = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AboutContainer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainContainer = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PlaylistItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SlideMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int VideosActivity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int VideosContainer = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
